all:
  hosts:
    ubuntu_init:        # alias Ansible, pas le vrai hostname
      ansible_host: 10.0.0.32
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ed25519

    ubuntu_new_ip:         # alias Ansible pour la nouvelle IP
      ansible_host: 10.0.0.30
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ed25519
